/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The audited SDK core version string. */
export declare function coreVersion(): string

/** One HTTP header (name/value pair) on the RFC 9421 request/response. */
export interface HttpHeader {
  key: string
  value: string
}

/** The RFC 9421 profile tag the signature is emitted/verified under. */
export declare function profileTag(): string

/** A signed RFC 9421 request. */
export interface SignedRequestJs {
  method: string
  targetUri: string
  headers: Array<HttpHeader>
  body: Buffer
  evidenceDigestAlg: string
  evidenceDigestValue: string
}

/** Sign an MCP request as an RFC 9421 + RFC 9530 message. */
export declare function signRequest(seed: Buffer, keyId: string, idJson: string, method: string, paramsJson: string, targetUri: string, audienceId: string, route: string | undefined | null, dpopToken: string, nonce: string, created: number, expires: number): SignedRequestJs

/** Verify a signed RFC 9421 response bound to the request the client sent. */
export declare function verifyResponse(status: number, respHeaders: Array<HttpHeader>, respBody: Buffer, reqMethod: string, reqTargetUri: string, reqHeaders: Array<HttpHeader>, reqBody: Buffer, reqEvidenceDigestAlg: string, reqEvidenceDigestValue: string, serverKeyId: string, serverPubkeyB64Url: string, serverRole: string, serverTrustDomain: string, serverSubject: string, now: number): VerifyResultJs

/** The outcome of verifying a signed RFC 9421 response. */
export interface VerifyResultJs {
  ok: boolean
  serverKeyid: string
}
