/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The outcome of verifying a delegated-signed bodyless `202 Accepted`.
 *
 * `ok` means the acknowledgement VERIFIED: the credential chained to the trusted root
 * and the delegated signature covered the acknowledgement AND bound it to the exact
 * notification transmission this client sent.
 *
 * **What that claims, exactly: the enforcement boundary authenticated and accepted the
 * message.** NOT that the action completed, that the inner application observed it, or
 * that anything was done about it — a verified acknowledgement of
 * `notifications/cancelled` does not mean anything was cancelled.
 */
export interface AcceptedResultJs {
  ok: boolean
  /**
   * The delegated key id that signed the acknowledgement — never the root, which
   * stays off the request path (ADR-MCPRE-052).
   */
  serverKeyid: string
}

/** The audited SDK core version string. */
export declare function coreVersion(): string

/** One HTTP header (name/value pair) on the RFC 9421 request/response. */
export interface HttpHeader {
  key: string
  value: string
}

/** The RFC 9421 profile tag the signature is emitted/verified under. */
export declare function profileTag(): string

/** A signed RFC 9421 request. */
export interface SignedRequestJs {
  method: string
  targetUri: string
  headers: Array<HttpHeader>
  body: Buffer
  evidenceDigestAlg: string
  evidenceDigestValue: string
}

/**
 * Sign a one-way MCP **notification** — a JSON-RPC message with a `method` and no
 * `id` — as an RFC 9421 + RFC 9530 message.
 *
 * Signed by the ordinary request rules; only the JSON-RPC envelope differs. The answer
 * is a signed bodyless `202`, checked with `verifyAccepted202`, not a bodied reply.
 * There are no continuation arguments: a message that receives no result cannot be an
 * ADR-MCPS-047 answer leg.
 */
export declare function signNotification(seed: Buffer, keyId: string, method: string, paramsJson: string, targetUri: string, audienceId: string, route: string | undefined | null, dpopToken: string, nonce: string, created: number, expires: number, bindingsJson?: string | undefined | null): SignedRequestJs

/**
 * Non-exporting-custody variant of `signNotification`: the private key never enters
 * the SDK. Wire-identical to the software path.
 */
export declare function signNotificationWithSigner(signCallback: (arg: Buffer) => Buffer, keyId: string, method: string, paramsJson: string, targetUri: string, audienceId: string, route: string | undefined | null, dpopToken: string, nonce: string, created: number, expires: number, bindingsJson?: string | undefined | null): SignedRequestJs

/**
 * Sign exact preimage bytes with a raw seed, returning the 64-byte detached Ed25519
 * signature — the primitive a `SigningDevice` (the HSM/KMS stand-in) is built on.
 *
 * This is the same operation the software signing path performs internally, so a
 * device-delegated signature is byte-identical to the in-process one.
 */
export declare function signPreimage(seed: Buffer, preimage: Buffer): Buffer

/** Sign an MCP request as an RFC 9421 + RFC 9530 message. */
export declare function signRequest(seed: Buffer, keyId: string, idJson: string, method: string, paramsJson: string, targetUri: string, audienceId: string, route: string | undefined | null, dpopToken: string, nonce: string, created: number, expires: number, contPrevAlg?: string | undefined | null, contPrevValue?: string | undefined | null, contIrrAlg?: string | undefined | null, contIrrValue?: string | undefined | null, contRequestState?: string | undefined | null, bindingsJson?: string | undefined | null): SignedRequestJs

/**
 * Sign an MCP request under NON-EXPORTING custody: the private key never enters the
 * SDK (ADR-MCPS-044 §Compliance).
 *
 * `signCallback` is the only thing held — `(preimage: Buffer) => Buffer` — a KMS/HSM
 * client call in production, invoked synchronously on the Node main thread. The SDK
 * composes the RFC 9421 signature base, hands those exact bytes to the device, and
 * takes back the detached Ed25519 signature; it never sees key material.
 *
 * The produced evidence is byte-identical to the software path for the same inputs —
 * the key has only moved behind the device. A device that cannot sign, or that
 * returns anything other than 64 signature bytes, fails closed as
 * `mcp-re.invalid_signature`.
 */
export declare function signRequestWithSigner(signCallback: (arg: Buffer) => Buffer, keyId: string, idJson: string, method: string, paramsJson: string, targetUri: string, audienceId: string, route: string | undefined | null, dpopToken: string, nonce: string, created: number, expires: number, contPrevAlg?: string | undefined | null, contPrevValue?: string | undefined | null, contIrrAlg?: string | undefined | null, contIrrValue?: string | undefined | null, contRequestState?: string | undefined | null, bindingsJson?: string | undefined | null): SignedRequestJs

/**
 * Verify the delegated-signed bodyless `202` a server returns for a one-way
 * notification, bound to the exact transmission this client sent.
 *
 * The binding is INSTANCE-level (owner ruling C019b): the acknowledgement covers
 * `mcp-re-request-evidence`, the digest of the request's own signature base, which
 * includes its nonce. An acknowledgement captured for one transmission therefore does
 * not verify for a byte-identical retransmission.
 */
export declare function verifyAccepted202(status: number, respHeaders: Array<HttpHeader>, respBody: Buffer, reqMethod: string, reqTargetUri: string, reqHeaders: Array<HttpHeader>, reqBody: Buffer, issuerKeyId: string, issuerPubkeyB64Url: string, issuerRole: string, issuerTrustDomain: string, issuerSubject: string, verifierAudiences: Array<string>, expectedAudienceHash: string, acceptedEpochs: Array<string>, maxClockSkew: number, revokedIdentifiers: Array<string>, now: number): AcceptedResultJs

/** Verify a delegated-required RFC 9421 response bound to the request the client sent. */
export declare function verifyResponse(status: number, respHeaders: Array<HttpHeader>, respBody: Buffer, reqMethod: string, reqTargetUri: string, reqHeaders: Array<HttpHeader>, reqBody: Buffer, reqEvidenceDigestAlg: string, reqEvidenceDigestValue: string, issuerKeyId: string, issuerPubkeyB64Url: string, issuerRole: string, issuerTrustDomain: string, issuerSubject: string, verifierAudiences: Array<string>, expectedAudienceHash: string, acceptedEpochs: Array<string>, maxClockSkew: number, revokedIdentifiers: Array<string>, now: number): VerifyResultJs

/** The outcome of verifying a delegated-required RFC 9421 response. */
export interface VerifyResultJs {
  ok: boolean
  serverKeyid: string
  /**
   * `"success"` for an accepted answer; `"rejection"` for a verified rejection
   * receipt — genuine evidence, but NOT an acceptance.
   */
  outcome: string
  /** The wire code carried by a verified rejection receipt; absent on success. */
  wireCode?: string
  /** Whether a rejection receipt is bound to this client's request. */
  bound: boolean
  /**
   * The ADR-MCPRE-058 §10 execution/retry contract the server derived from its
   * exchange machine and signed into the rejection body. Absent on success and on a
   * receipt that stated nothing.
   *
   * An ABSENT `execution_status` is not `"not_executed"`. The server states a
   * disposition when it has one, and collapsing silence into "nothing ran" is
   * exactly the read that makes a post-dispatch refusal look retry-safe.
   */
  executionStatus?: string
  /** `retry_safety`: what a retry of this refused request would cost. */
  retrySafety?: string
  /** `continuation_status`: whether the exchange consumed a human approval. */
  continuationStatus?: string
  /** `retention_status`: whether the server's evidence-retention obligation failed. */
  retentionStatus?: string
  /**
   * The verified response's evidence-handle digest algorithm — the
   * `input_required_response_evidence` handle an MRTR answer leg binds to
   * (ADR-MCPS-047). Read from the VERIFIED response only.
   */
  respEvidenceDigestAlg: string
  /** The verified response's evidence-handle digest value (base64url, no pad). */
  respEvidenceDigestValue: string
  /**
   * `result.requestState` (a string) from the verified response body IFF the
   * audited classifier reads it as an `InputRequiredResult`; else absent. The
   * opaque MRTR state the answer leg re-presents. Read only after the response
   * verified as genuine evidence.
   *
   * The discriminator itself is deliberately not restated here — it lives in
   * `mcp_re_http_profile::result_class`, and a doc comment repeating it is one
   * more copy to drift. A verified reply that declares itself non-terminal
   * without a usable state is an ERROR, never an absent state.
   */
  requestState?: string
}
