"""Materialize the host copy of the admission gate and point every runner at it.

    python3 tools/slo/install_arbiter.py --verify     # refuse unless the installed copy
                                                      # is this checkout's
    python3 tools/slo/install_arbiter.py --check      # report only, change nothing
    python3 tools/slo/install_arbiter.py --apply      # install + configure .env
    python3 tools/slo/install_arbiter.py --apply --vm # also configure the colima VM runner

WHY THE HOST COPY LIVES OUTSIDE THE RUNNER DIRECTORIES
======================================================

A runner application rewrites its own tree on self-update and `config.sh remove` deletes it
outright, so a hook installed inside `actions-runner/` is one update away from vanishing --
and a vanished pre-job hook fails OPEN, silently, at exactly the moment admission matters.
The runner directories therefore hold only an `.env` REFERENCE to the installed copy.

WHAT IT DOES NOT DO
===================

It never restarts a runner. `.env` is consumed by the listener at startup, so a restart is
required for changes to take effect, but restarting is an operator action: on dev1 the
listener is a system-domain LaunchDaemon needing sudo, and on any runner a restart during a
live job is not this script's decision to make.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

ROOT = Path(os.environ.get("MCP_RE_ARBITER_ROOT", "/opt/verification/runner-arbiter"))
MIRROR = Path(os.environ.get("MCP_RE_ARBITER_MIRROR", str(Path.home() / ".runner-arbiter")))

MACOS_RUNNERS = (
    Path("/Users/mats/dev/actions-runner"),
    Path("/Users/mats/dev/actions-runner-mcp-re"),
)

VM_PROFILE = os.environ.get("MCP_RE_ARBITER_VM_PROFILE", "gh-runner")
VM_RUNNER_HOME = os.environ.get("MCP_RE_ARBITER_VM_RUNNER_HOME", "/home/mats.guest/actions-runner")
COLIMA = os.environ.get("MCP_RE_ARBITER_COLIMA", "/opt/homebrew/bin/colima")

SOURCES = ("host_gate.py", "vm_participant.py", "job_identity.py",
           "arbiter_error.py", "runner_arbiter.py", "environment_preflight.py",
           "run_supervisor.py")

STARTED_VAR = "ACTIONS_RUNNER_HOOK_JOB_STARTED"
COMPLETED_VAR = "ACTIONS_RUNNER_HOOK_JOB_COMPLETED"

# The wrappers are generated rather than shipped, so the installed hook always matches the
# installed layout and cannot drift from it.
WRAPPER = """#!/bin/sh
# Generated by tools/slo/install_arbiter.py -- do not edit by hand.
# A non-zero exit here means the runner does NOT execute the job. That is how host
# admission refuses work, and it is the only point at which a job can still be refused.
exec /usr/bin/env python3 {root}/bin/runner_arbiter.py {command}
"""

VM_WRAPPER = """#!/bin/sh
# Generated by tools/slo/install_arbiter.py -- do not edit by hand.
# Runs inside the colima VM. Reads the committed gate over virtiofs and gates this
# runner; it never takes a lock across the kernel boundary.
exec /usr/bin/env python3 {mirror}/bin/vm_admission_hook.py {command}
"""


def vm_ssh(*args: str, timeout: int = 120) -> subprocess.CompletedProcess:
    return subprocess.run([COLIMA, "ssh", "-p", VM_PROFILE, "--", *args],
                          capture_output=True, text=True, timeout=timeout)


def env_lines(path: Path) -> list[str]:
    try:
        return path.read_text().splitlines()
    except FileNotFoundError:
        return []


def env_with_hooks(lines: list[str], started: str, completed: str) -> list[str]:
    """Set both hook variables, preserving every other line exactly as it was."""
    kept = [ln for ln in lines
            if not ln.strip().startswith((STARTED_VAR + "=", COMPLETED_VAR + "="))]
    return kept + [f"{STARTED_VAR}={started}", f"{COMPLETED_VAR}={completed}"]


def installed_drift(root: Path = ROOT, mirror: Path = MIRROR, here: Path = HERE) -> list[dict]:
    """Does the code that will DECIDE equal the code in this checkout?

    The SLO lane executes `/opt/verification/runner-arbiter/bin/*.py`, and what those files
    answer is EVIDENCE: `physical_host_exclusive: true` is an assertion a reader takes on the
    strength of the source in this repository. Nothing established that the installed copy IS
    that source. `install_host` only ever writes — `--check` reported directory and `.env`
    state and never compared a byte — so an edit on the host, a partial install, or a copy
    left behind by an older revision would decide a measurement while every file in the tree
    read as correct.

    A checked-out copy cannot be verified by the installed one: an installed file that had
    drifted would be answering the question about itself. So this comparison belongs here, in
    the checkout, and the lane must run it from the checkout.

    Generated wrappers are compared to a REGENERATION rather than to a stored copy, because
    their content is derived from `ROOT` and a stored expectation would be a second place
    deciding what they say.
    """
    drift = [_compare(here / name, root / "bin" / name) for name in SOURCES]
    drift.append(_compare(here / "vm_admission_hook.py", mirror / "bin" / "vm_admission_hook.py"))
    for command, filename in (("job-started", "job-started.sh"),
                              ("job-completed", "job-completed.sh")):
        drift.append(_expect(root / "bin" / filename, WRAPPER.format(root=root, command=command)))
    for command, filename in (("job-started", "vm-job-started.sh"),
                              ("job-completed", "vm-job-completed.sh")):
        # VM_WRAPPER, not WRAPPER. These two templates differ in the interpreter path they
        # exec -- the VM's names `vm_admission_hook.py` under the mirror, because /opt is
        # not mounted in the guest at all. Comparing the VM wrapper against the HOST
        # template asked whether a file in the VM contained a /opt path it could never
        # contain, so `--verify` returned 1 no matter what was installed. That is a FALSE
        # RED on the gate at slo.yml:168, and the worst kind: the lane reported drift
        # while the installed bytes were exactly what the installer writes.
        drift.append(_expect(mirror / "bin" / filename,
                             VM_WRAPPER.format(mirror=mirror, command=command)))
    return drift


def _compare(source: Path, installed: Path) -> dict:
    """One tracked file against its installed copy."""
    if not installed.is_file():
        return {"file": str(installed), "state": "ABSENT", "source": str(source)}
    state = "MATCHES" if installed.read_bytes() == source.read_bytes() else "DIFFERS"
    return {"file": str(installed), "state": state, "source": str(source)}


def _expect(installed: Path, expected: str) -> dict:
    """One generated wrapper against a regeneration of what it should say."""
    if not installed.is_file():
        return {"file": str(installed), "state": "ABSENT", "source": "generated"}
    state = "MATCHES" if installed.read_text() == expected else "DIFFERS"
    return {"file": str(installed), "state": state, "source": "generated"}


def verify(root: Path = ROOT, mirror: Path = MIRROR, here: Path = HERE) -> int:
    """Fail closed on any drift. ABSENT and DIFFERS are both refusals, for one reason.

    An absent file is not "nothing to compare": the lane will execute that path, and a path
    that is not there at verification time is a host whose admission code is unknown.
    """
    drift = installed_drift(root, mirror, here)
    print(json.dumps({"arbiter_provenance": drift}, indent=2))
    bad = [row for row in drift if row["state"] != "MATCHES"]
    if bad:
        print(
            f"\narbiter provenance: FAIL — {len(bad)} of {len(drift)} installed file(s) are "
            "not this checkout's.\nThe host arbiter decides whether the SLO lane may measure "
            "and asserts physical-host exclusivity; that verdict is evidence. Re-install with "
            "`--apply` and restart the listeners, or do not measure.",
            file=sys.stderr,
        )
        return 1
    print(f"\narbiter provenance: OK — {len(drift)} installed file(s) are this checkout's.")
    return 0


def selftest() -> int:
    """The mutation probe. A comparison that cannot be shown to fail compares nothing."""
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp)
        src, root, mirror = base / "src", base / "root", base / "mirror"
        (root / "bin").mkdir(parents=True)
        (mirror / "bin").mkdir(parents=True)
        src.mkdir()
        for name in SOURCES + ("vm_admission_hook.py",):
            (src / name).write_text(f"# {name}\n")
            if name in SOURCES:
                shutil.copy2(src / name, root / "bin" / name)
        shutil.copy2(src / "vm_admission_hook.py", mirror / "bin" / "vm_admission_hook.py")
        for command, filename in (("job-started", "job-started.sh"),
                                  ("job-completed", "job-completed.sh")):
            (root / "bin" / filename).write_text(WRAPPER.format(root=root, command=command))
        for command, filename in (("job-started", "vm-job-started.sh"),
                                  ("job-completed", "vm-job-completed.sh")):
            (mirror / "bin" / filename).write_text(WRAPPER.format(root=root, command=command))

        assert verify(root, mirror, src) == 0, "an exact install must verify"

        edited = root / "bin" / SOURCES[0]
        edited.write_text(edited.read_text() + "# edited on the host\n")
        assert verify(root, mirror, src) == 1, "an edited installed file must refuse"
        shutil.copy2(src / SOURCES[0], edited)
        assert verify(root, mirror, src) == 0, "restoring it must verify again"

        (mirror / "bin" / "vm_admission_hook.py").unlink()
        assert verify(root, mirror, src) == 1, "an absent VM hook must refuse, not pass"
        shutil.copy2(src / "vm_admission_hook.py", mirror / "bin" / "vm_admission_hook.py")

        wrapper = root / "bin" / "job-started.sh"
        wrapper.write_text(wrapper.read_text().replace("runner_arbiter.py", "true #"))
        assert verify(root, mirror, src) == 1, (
            "a wrapper that no longer calls the arbiter must refuse — that is the edit that "
            "makes admission fail OPEN, and it is invisible to a file-presence check"
        )
    print("install_arbiter selftest: OK")
    return 0


def install_host(apply: bool) -> dict:
    report: dict = {"root": str(ROOT), "mirror": str(MIRROR), "actions": []}
    bin_dir = ROOT / "bin"
    mirror_bin = MIRROR / "bin"

    if apply:
        for d in (ROOT, bin_dir, ROOT / "active", MIRROR, mirror_bin, MIRROR / "vm-active"):
            d.mkdir(parents=True, exist_ok=True)
        for name in SOURCES:
            shutil.copy2(HERE / name, bin_dir / name)
        # The VM executes this one over virtiofs, so it lives in the shared mirror.
        shutil.copy2(HERE / "vm_admission_hook.py", mirror_bin / "vm_admission_hook.py")

        for command, filename in (("job-started", "job-started.sh"),
                                  ("job-completed", "job-completed.sh")):
            target = bin_dir / filename
            target.write_text(WRAPPER.format(root=ROOT, command=command))
            target.chmod(0o755)
            report["actions"].append(f"wrote {target}")

        for command, filename in (("job-started", "vm-job-started.sh"),
                                  ("job-completed", "vm-job-completed.sh")):
            target = mirror_bin / filename
            target.write_text(VM_WRAPPER.format(mirror=MIRROR, command=command))
            target.chmod(0o755)
            report["actions"].append(f"wrote {target}")

    report["host_installed"] = (ROOT / "bin" / "runner_arbiter.py").exists()
    report["vm_hook_published"] = (mirror_bin / "vm_admission_hook.py").exists()
    return report


def configure_macos_runners(apply: bool) -> list[dict]:
    started = str(ROOT / "bin" / "job-started.sh")
    completed = str(ROOT / "bin" / "job-completed.sh")
    out = []
    for runner in MACOS_RUNNERS:
        entry = {"runner": runner.name, "path": str(runner), "present": runner.exists()}
        if not runner.exists():
            out.append(entry)
            continue
        env_path = runner / ".env"
        current = env_lines(env_path)
        desired = env_with_hooks(current, started, completed)
        entry["already_configured"] = (current == desired)
        if apply and not entry["already_configured"]:
            # Rewritten whole, preserving unrelated lines: an .env is small and a partial
            # edit is how a PATH line gets lost.
            env_path.write_text("\n".join(desired) + "\n")
            entry["written"] = True
        entry["env_now"] = env_lines(env_path)
        out.append(entry)
    return out


def configure_vm_runner(apply: bool) -> dict:
    entry: dict = {"runner": "dev1-linux", "profile": VM_PROFILE}
    try:
        if vm_ssh("true", timeout=30).returncode != 0:
            entry["reachable"] = False
            return entry
    except (OSError, subprocess.SubprocessError) as exc:
        entry["reachable"] = False
        entry["detail"] = str(exc)
        return entry
    entry["reachable"] = True

    started = f"{MIRROR}/bin/vm-job-started.sh"
    completed = f"{MIRROR}/bin/vm-job-completed.sh"
    current = (vm_ssh("sh", "-c", f"cat {VM_RUNNER_HOME}/.env 2>/dev/null || true").stdout or "")
    desired = env_with_hooks(current.splitlines(), started, completed)
    entry["already_configured"] = (current.splitlines() == desired)

    # The VM must actually be able to reach and execute the published hook. A declared hook
    # that the VM cannot run is not participation -- it is a silent fail-open.
    entry["hook_visible_in_vm"] = (
        vm_ssh("sh", "-c", f"test -x '{started}' && echo yes || echo no").stdout or ""
    ).strip() == "yes"

    if apply and not entry["already_configured"]:
        body = "\n".join(desired) + "\n"
        result = vm_ssh("sh", "-c",
                        f"cat > {VM_RUNNER_HOME}/.env <<'ARBITER_ENV_EOF'\n{body}ARBITER_ENV_EOF")
        entry["written"] = result.returncode == 0
        entry["detail"] = (result.stderr or "").strip()[:200]
    entry["env_now"] = (
        vm_ssh("sh", "-c", f"cat {VM_RUNNER_HOME}/.env 2>/dev/null || true").stdout or ""
    ).splitlines()
    return entry


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="report only, change nothing (the default)")
    ap.add_argument("--apply", action="store_true", help="make changes")
    ap.add_argument("--vm", action="store_true", help="also configure the colima VM runner")
    ap.add_argument("--verify", action="store_true",
                    help="refuse unless every installed file is this checkout's")
    ap.add_argument("--selftest", action="store_true", help="the mutation probe")
    args = ap.parse_args(argv)

    if args.selftest:
        return selftest()
    if args.verify:
        return verify()

    report = {
        "mode": "apply" if args.apply else "check",
        "host": install_host(args.apply),
        "macos_runners": configure_macos_runners(args.apply),
    }
    if args.vm:
        report["vm_runner"] = configure_vm_runner(args.apply)

    print(json.dumps(report, indent=2, default=str))

    pending = [r["runner"] for r in report["macos_runners"]
               if r.get("present") and not r.get("already_configured")]
    if pending and not args.apply:
        print(f"\nnot yet configured: {pending} — re-run with --apply", file=sys.stderr)
    print("\nNOTE: .env is consumed by the runner listener at startup. A restart is required "
          "before any of this takes effect, and this script deliberately does not perform "
          "one.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
