// SPDX-License-Identifier: Apache-2.0
//! external → us: the MCP-RE verifier accepts a compact-JWS delegation credential
//! produced by an INDEPENDENT JOSE/EdDSA implementation (ADR-MCPRE-052 §9;
//! mirrors the RFC 9421 gate, MCPRE-99).
//!
//! `external_delegation_kat.json` is generated by `tools/jose_cross_verify.py`
//! using `python-cryptography` — a different Ed25519 implementation than the
//! `ed25519-dalek` the corpus is signed with. This test verifies that external
//! credential under `verify_delegation_credential`, and confirms the MCP-RE issuer
//! reproduces the identical compact JWS byte-for-byte (Ed25519 is deterministic),
//! closing the interop loop in both directions.
//!
//! The complementary direction (our committed credential verifies under the
//! external impl) runs in `tools/jose_cross_verify.py`, the CI no-merge gate.
//!
//! Regenerate the external vector:
//!   python3 mcp-re-conformance/tools/jose_cross_verify.py --emit-external-kat

use serde::Deserialize;

use mcp_re_core::b64url_decode;
use mcp_re_core::SigningKey;
use mcp_re_core::VerificationKey;
use mcp_re_http_profile::issue_delegation_credential;
use mcp_re_http_profile::verify_delegation_credential;
use mcp_re_http_profile::Audience;
use mcp_re_http_profile::Cnf;
use mcp_re_http_profile::DelegatedJwk;
use mcp_re_http_profile::DelegationClaims;
use mcp_re_http_profile::DelegationHeader;
use mcp_re_http_profile::DelegationVerifyParams;
use mcp_re_http_profile::DELEGATION_ALG;
use mcp_re_http_profile::DELEGATION_TYP;
use mcp_re_http_profile::JWK_CRV_ED25519;
use mcp_re_http_profile::JWK_KTY_OKP;
use mcp_re_http_profile::KEY_USE_RESPONSE_SIGNING;

#[derive(Debug, Deserialize)]
struct ExternalKat {
    #[allow(dead_code)]
    note: String,
    root_seed_b64url: String,
    root_public_key_b64url: String,
    delegated_seed_b64url: String,
    delegated_public_key_b64url: String,
    issuer_kid: String,
    delegated_kid: String,
    verifier_audience: String,
    expected_profile: String,
    expected_audience_hash: String,
    expected_server_signer: String,
    trust_epoch: String,
    now_unix: i64,
    max_clock_skew: i64,
    compact_jws: String,
}

fn corpus_dir() -> std::path::PathBuf {
    if let Ok(rel) = std::env::var("MCP_RE_DELEGATION_VECTORS_MANIFEST") {
        for key in ["TEST_SRCDIR", "RUNFILES_DIR"] {
            if let Ok(root) = std::env::var(key) {
                let candidate = std::path::Path::new(&root).join(&rel);
                if candidate.exists() {
                    return candidate.parent().expect("parent").to_path_buf();
                }
            }
        }
        let candidate = std::path::PathBuf::from(&rel);
        if candidate.exists() {
            return candidate.parent().expect("parent").to_path_buf();
        }
    }
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("vectors")
        .join("delegation-profile")
}

fn load() -> ExternalKat {
    let path = corpus_dir().join("external_delegation_kat.json");
    serde_json::from_slice(&std::fs::read(&path).expect("external_delegation_kat.json committed"))
        .expect("external_delegation_kat.json parses")
}

fn seed32(b64url: &str) -> [u8; 32] {
    let bytes = b64url_decode(b64url).expect("seed is base64url");
    bytes.try_into().expect("seed is 32 bytes")
}

/// Reconstruct the credential the external tool signed, using the frozen KAT
/// constants — so re-minting with our issuer must reproduce the exact bytes.
fn claims_from(kat: &ExternalKat) -> DelegationClaims {
    DelegationClaims {
        iss: "did:example:server".into(),
        iat: 1_700_000_000,
        nbf: 1_700_000_000,
        exp: 1_700_000_300,
        jti: "evt-1".into(),
        aud: Audience::One(kat.verifier_audience.clone()),
        mcp_re_profile: kat.expected_profile.clone(),
        mcp_re_audience_hash: kat.expected_audience_hash.clone(),
        mcp_re_server_signer: kat.expected_server_signer.clone(),
        mcp_re_key_use: KEY_USE_RESPONSE_SIGNING.into(),
        delegated_kid: kat.delegated_kid.clone(),
        issuer_kid: kat.issuer_kid.clone(),
        trust_epoch: kat.trust_epoch.clone(),
        cnf: Cnf {
            jwk: DelegatedJwk {
                kty: JWK_KTY_OKP.into(),
                crv: JWK_CRV_ED25519.into(),
                kid: kat.delegated_kid.clone(),
                x: kat.delegated_public_key_b64url.clone(),
            },
        },
    }
}

/// external → us: the externally-minted credential verifies under our verifier.
#[test]
fn external_credential_verifies_under_our_verifier() {
    let kat = load();
    let root_pub = VerificationKey::from_b64url(&kat.root_public_key_b64url)
        .expect("root public key parses");
    let issuer_kid = kat.issuer_kid.clone();

    let audiences = [kat.verifier_audience.as_str()];
    let epochs = [kat.trust_epoch.as_str()];
    let params = DelegationVerifyParams {
        now: kat.now_unix,
        max_clock_skew: kat.max_clock_skew,
        verifier_audiences: &audiences,
        expected_profile: &kat.expected_profile,
        expected_audience_hash: &kat.expected_audience_hash,
        expected_server_signer: &kat.expected_server_signer,
        accepted_epochs: &epochs,
    };

    let verified = verify_delegation_credential(
        &kat.compact_jws,
        &params,
        |kid: &str| {
            if kid == issuer_kid {
                Some(root_pub.clone())
            } else {
                None
            }
        },
        |_kid: &str| false,
    )
    .expect("external credential verifies under the MCP-RE verifier");

    assert_eq!(verified.delegated_kid, kat.delegated_kid);
    assert_eq!(
        verified.delegated_key.to_b64url(),
        kat.delegated_public_key_b64url
    );
    assert_eq!(verified.issuer_kid, kat.issuer_kid);
}

/// Determinism / us → external byte agreement: re-minting the same claims with
/// our issuer reproduces the external tool's compact JWS byte-for-byte.
#[test]
fn our_issuer_reproduces_the_external_bytes() {
    let kat = load();
    let root = SigningKey::from_seed_bytes(&seed32(&kat.root_seed_b64url));
    // The delegated public key in the KAT must be the one our seed derives.
    let delegated = SigningKey::from_seed_bytes(&seed32(&kat.delegated_seed_b64url));
    assert_eq!(
        delegated.public_key().to_b64url(),
        kat.delegated_public_key_b64url,
        "delegated seed disagrees with the KAT public key"
    );

    let header = DelegationHeader {
        typ: DELEGATION_TYP.into(),
        alg: DELEGATION_ALG.into(),
        kid: kat.issuer_kid.clone(),
    };
    let ours = issue_delegation_credential(&root, &header, &claims_from(&kat));
    assert_eq!(
        ours, kat.compact_jws,
        "MCP-RE issuer diverged byte-for-byte from the independent JOSE build"
    );
}
