// SPDX-License-Identifier: Apache-2.0
//! external → us: the MCP-RE verifier accepts an Ed25519 signature produced by
//! an INDEPENDENT RFC 9421 implementation (ADR-MCPRE-050 no-merge gate,
//! MCPRE-99).
//!
//! `external_kat.json` is generated by `tools/rfc9421_cross_verify.py` using
//! `python-cryptography` — a different Ed25519 implementation than the
//! `ed25519-dalek` the corpus was signed with. This test verifies that external
//! signature over its exact base with the MCP-RE core verifier, and also
//! confirms the MCP-RE signer reproduces the identical signature byte-for-byte
//! (Ed25519 is deterministic), closing the interop loop in both directions.
//!
//! The complementary direction (our vectors verify under the external impl) runs
//! in `tools/rfc9421_cross_verify.py`, which is the CI no-merge gate.
//!
//! Regenerate the external vector:
//!   python3 mcp-re-conformance/tools/rfc9421_cross_verify.py --emit-external-kat

use serde::Deserialize;

use mcp_re_core::b64url_decode;
use mcp_re_core::verify_ed25519_with;
use mcp_re_core::McpReError;
use mcp_re_core::SigningKey;

#[derive(Debug, Deserialize)]
struct ExternalKat {
    #[allow(dead_code)]
    note: String,
    seed_b64url: String,
    public_key_b64url: String,
    signature_base_b64url: String,
    signature_b64url: String,
}

fn corpus_dir() -> std::path::PathBuf {
    if let Ok(rel) = std::env::var("MCP_RE_HTTP_PROFILE_VECTORS_MANIFEST") {
        for key in ["TEST_SRCDIR", "RUNFILES_DIR"] {
            if let Ok(root) = std::env::var(key) {
                let candidate = std::path::Path::new(&root).join(&rel);
                if candidate.exists() {
                    return candidate.parent().expect("parent").to_path_buf();
                }
            }
        }
        let candidate = std::path::PathBuf::from(&rel);
        if candidate.exists() {
            return candidate.parent().expect("parent").to_path_buf();
        }
    }
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("vectors")
        .join("http-profile")
}

fn load() -> ExternalKat {
    let path = corpus_dir().join("external_kat.json");
    serde_json::from_slice(&std::fs::read(&path).expect("external_kat.json committed"))
        .expect("external_kat.json parses")
}

#[test]
fn mcp_re_verifier_accepts_an_externally_produced_signature() {
    let kat = load();
    let seed: [u8; 32] = b64url_decode(&kat.seed_b64url)
        .expect("seed b64url")
        .try_into()
        .expect("seed is 32 bytes");
    let base = b64url_decode(&kat.signature_base_b64url).expect("base b64url");
    let signing = SigningKey::from_seed_bytes(&seed);
    let verifying = signing.public_key();

    // external → us: the signature `cryptography` produced verifies here.
    verify_ed25519_with(
        &base,
        &kat.signature_b64url,
        &verifying,
        McpReError::InvalidSignature,
    )
    .expect("independent RFC 9421 signature verifies under the MCP-RE verifier");
}

#[test]
fn key_and_signature_agree_byte_for_byte_across_implementations() {
    let kat = load();
    let seed: [u8; 32] = b64url_decode(&kat.seed_b64url)
        .expect("seed b64url")
        .try_into()
        .expect("seed is 32 bytes");
    let base = b64url_decode(&kat.signature_base_b64url).expect("base b64url");
    let signing = SigningKey::from_seed_bytes(&seed);

    // The two implementations derive the same public key from the seed...
    let our_pub = mcp_re_core::b64url_encode(&signing.public_key().to_bytes());
    assert_eq!(
        our_pub, kat.public_key_b64url,
        "public keys diverge across impls"
    );

    // ...and produce the identical deterministic Ed25519 signature.
    let our_sig = signing.sign(&base);
    assert_eq!(
        our_sig, kat.signature_b64url,
        "signatures diverge across impls — Ed25519 determinism broken or base mismatch"
    );
}
