// SPDX-License-Identifier: Apache-2.0
//! A retained-evidence corpus MCP-RE produced, and what it establishes — issue #740.
//!
//! # Why this exists beside `interop/`, and does not replace it
//!
//! The frozen `s01` interop corpus records `produced_by: "@transmute/cose 0.3.0 + node
//! crypto Ed25519"`, and *no MCP-RE code produced any of it* is the whole value of that
//! vector: it is the only evidence a foreign implementation reads MCP-RE statements.
//! Regenerating it would destroy a real interop claim to fix a different one, so it stays
//! as it is, demoted in place.
//!
//! What it cannot do is evidence retained-evidence CORRESPONDENCE over a real call. Its
//! `retained-evidence.bin` carries the handles `req-0`/`rsp-0` rather than the submitted
//! messages, so the submission digest is not reproducible from it at all — the artifact
//! cannot be made to bind a submission by any change on the verifier's side. Closing that
//! is a corpus-GENERATION job, and this is it.
//!
//! # What this corpus establishes
//!
//! A three-hop MCP-RE exchange, every hop signed by the shipped signers and verified by
//! the shipped verifier, reconstructed into the record an auditor holds, and committed to
//! by a Signed Statement this crate issued. The statement's `submitted_commitment` is the
//! digest `reconstruct_chain` computed over the SUBMITTED hops, so
//! `verify_retained_evidence` can reach the verdict the frozen corpus cannot:
//! `BoundToVerifiedCall`.
//!
//! # What it does NOT establish
//!
//! Interoperability. Every byte here is MCP-RE's own, which is exactly the property `s01`
//! has and this does not — the two corpora answer different questions and neither
//! substitutes for the other. Nothing here says anything about registration, about a
//! transparency service, or about the confidentiality of retained evidence.
//!
//! # Frozen bytes, and a writer that regenerates them
//!
//! Two directions, the established `write_http_profile_fixtures` pattern:
//!
//!   1. the writer (`write_retained_corpus -- --ignored`) regenerates the corpus with the
//!      project's own implementation, so committed bytes and regenerated bytes are
//!      compared rather than assumed;
//!   2. the frozen runner verifies the COMMITTED bytes, so a change that alters what the
//!      implementation emits is visible as a diff rather than absorbed silently.
//!
//! Regenerate: `cargo test -p mcp-re-conformance --test scitt_retained_corpus_test \
//!   write_retained_corpus -- --ignored --exact`

use std::path::PathBuf;

use mcp_re_core::SigningKey;
use mcp_re_http_profile::chain::ChainLabel;
use mcp_re_http_profile::reconstruct_chain;
use mcp_re_http_profile::scitt::verify_retained_evidence;
use mcp_re_http_profile::scitt::EvidenceCommitment;
use mcp_re_http_profile::scitt::RetainedCorrespondence;
use mcp_re_http_profile::scitt::SignedStatement;
use mcp_re_http_profile::ActorIdentity;
use mcp_re_http_profile::ArtifactBinding;
use mcp_re_http_profile::ArtifactType;
use mcp_re_http_profile::AudienceTuple;
use mcp_re_http_profile::ChainAudit;
use mcp_re_http_profile::HttpContinuation;
use mcp_re_http_profile::HttpProfileError;
use mcp_re_http_profile::HttpRequest;
use mcp_re_http_profile::HttpRequestEvidenceBlock;
use mcp_re_http_profile::HttpResponse;
use mcp_re_http_profile::RequestEvidence;
use mcp_re_http_profile::RequestEvidenceDigest;
use mcp_re_http_profile::ResolvedActor;
use mcp_re_http_profile::RetainedHop;
use mcp_re_http_profile::SignerSlot;
use mcp_re_http_profile::VerifierPolicy;

// ---------------------------------------------------------------------------
// Fixed material. Every seed and instant is a constant so the corpus is reproducible:
// a fixture whose bytes depend on when it was generated cannot be regenerated and
// compared, which is the whole point of the writer.
// ---------------------------------------------------------------------------

const TARGET: &str = "https://mcp.example.com/mcp";
const CLIENT_KEY_ID: &str = "client-key-1";
const SERVER_KEY_ID: &str = "server-key-1";
const DELEGATED_KID: &str = "server-key-1/delegated/1";
const ISSUER_KID: &str = "scitt-issuer-1";
const CREATED: i64 = 1_700_000_000;
const EXPIRES: i64 = 1_700_000_300;
const NOW: i64 = 1_700_000_100;
const AWAITING: &str = r#"{"jsonrpc":"2.0","id":1,"result":{"resultType":"input_required"}}"#;
const DONE: &str = r#"{"jsonrpc":"2.0","id":1,"result":{"ok":true}}"#;

fn client_key() -> SigningKey {
    SigningKey::from_seed_bytes(&[11u8; 32])
}

fn server_key() -> SigningKey {
    SigningKey::from_seed_bytes(&[22u8; 32])
}

fn delegated_key() -> SigningKey {
    SigningKey::from_seed_bytes(&[66u8; 32])
}

fn issuer_key() -> SigningKey {
    SigningKey::from_seed_bytes(&[77u8; 32])
}

fn audience() -> AudienceTuple {
    AudienceTuple {
        audience_id: "mcp.example.com".into(),
        target_uri: TARGET.into(),
        route: Some("tools/call".into()),
    }
}

/// The block names the DELEGATED key — the key that actually signed the response — while
/// the trust seam resolves the ROOT the credential chains to.
fn server_signer() -> ActorIdentity {
    ActorIdentity {
        role: "server".into(),
        trust_domain: "example.com".into(),
        subject: "did:example:server".into(),
        keyid: DELEGATED_KID.into(),
    }
}

fn block(continuation: Option<HttpContinuation>) -> HttpRequestEvidenceBlock {
    HttpRequestEvidenceBlock {
        profile: mcp_re_http_profile::PROFILE_TAG.into(),
        audience: audience(),
        artifact_bindings: vec![ArtifactBinding::opaque_digest(
            ArtifactType::OauthDpop,
            b"tok",
        )],
        continuation,
        admission: None,
        admission_assertion: None,
        authorization_decision: None,
    }
}

fn resolver() -> impl Fn(&str, SignerSlot) -> Option<ResolvedActor> {
    move |key_id: &str, slot: SignerSlot| {
        let (role, key) = match (key_id, slot) {
            (CLIENT_KEY_ID, SignerSlot::Request) => ("client", client_key()),
            (SERVER_KEY_ID, SignerSlot::Response) => ("server", server_key()),
            _ => return None,
        };
        Some(ResolvedActor {
            identity: ActorIdentity {
                role: role.into(),
                trust_domain: "example.com".into(),
                subject: format!("did:example:{role}"),
                keyid: key_id.into(),
            },
            verification_key: key.public_key(),
            slot,
        })
    }
}

fn credential() -> String {
    let d = delegated_key();
    let header = mcp_re_http_profile::DelegationHeader {
        typ: mcp_re_http_profile::DELEGATION_TYP.into(),
        alg: mcp_re_http_profile::DELEGATION_ALG.into(),
        kid: SERVER_KEY_ID.into(),
    };
    let claims = mcp_re_http_profile::DelegationClaims {
        iss: "did:example:server".into(),
        iat: CREATED,
        nbf: CREATED,
        exp: EXPIRES,
        jti: "evt-retained".into(),
        aud: mcp_re_http_profile::Audience::One("did:example:server".into()),
        mcp_re_profile: mcp_re_http_profile::PROFILE_TAG.into(),
        mcp_re_audience_hash: "aud-scope-1".into(),
        mcp_re_server_signer: server_signer().actor_id(),
        mcp_re_key_use: mcp_re_http_profile::KEY_USE_RESPONSE_SIGNING.into(),
        delegated_kid: DELEGATED_KID.into(),
        issuer_kid: SERVER_KEY_ID.into(),
        trust_epoch: "epoch-1".into(),
        cnf: mcp_re_http_profile::Cnf {
            jwk: mcp_re_http_profile::DelegatedJwk {
                kty: mcp_re_http_profile::JWK_KTY_OKP.into(),
                crv: mcp_re_http_profile::JWK_CRV_ED25519.into(),
                kid: DELEGATED_KID.into(),
                x: d.public_key().to_b64url(),
            },
        },
    };
    mcp_re_http_profile::issue_delegation_credential(&server_key(), &header, &claims)
}

fn expectations() -> mcp_re_http_profile::DelegationExpectations<'static> {
    mcp_re_http_profile::DelegationExpectations {
        verifier_audiences: &["did:example:server"],
        expected_audience_hash: "aud-scope-1",
        accepted_epochs: &["epoch-1"],
        max_clock_skew: 60,
    }
}

fn nothing_revoked(_: &str) -> bool {
    false
}

fn artifact_material(_: &ArtifactBinding) -> Option<Vec<u8>> {
    Some(b"tok".to_vec())
}

static ARTIFACT_MATERIAL: fn(&ArtifactBinding) -> Option<Vec<u8>> = artifact_material;

fn audit() -> ChainAudit<'static> {
    static AUD: std::sync::OnceLock<AudienceTuple> = std::sync::OnceLock::new();
    ChainAudit {
        expected_audience: AUD.get_or_init(audience),
        artifact_material: &ARTIFACT_MATERIAL,
    }
}

fn to_digest(e: &RequestEvidence) -> RequestEvidenceDigest {
    RequestEvidenceDigest {
        digest_alg: e.digest_alg.clone(),
        digest_value: e.digest_value.clone(),
    }
}

/// Sign one hop with the shipped signers and return it with the two role-labeled handles
/// the next hop's continuation must name.
fn hop(
    nonce: &str,
    continuation: Option<HttpContinuation>,
    body: &str,
) -> (RetainedHop, RequestEvidence, RequestEvidence) {
    let mut request = HttpRequest {
        method: "POST".into(),
        target_uri: TARGET.into(),
        headers: vec![("Content-Type".into(), "application/json".into())],
        body: br#"{"jsonrpc":"2.0","id":1,"method":"tools/call"}"#.to_vec(),
    };
    let req_evidence = mcp_re_http_profile::sign_request_full(
        &mut request,
        &block(continuation),
        &client_key(),
        CLIENT_KEY_ID,
        CREATED,
        EXPIRES,
        nonce,
    )
    .expect("request signs");

    let mut response = HttpResponse {
        status: 200,
        headers: vec![("Content-Type".into(), "application/json".into())],
        body: body.as_bytes().to_vec(),
    };
    // DELEGATED, because that is the only response mode the serving path has.
    mcp_re_http_profile::sign_delegated_response_full(
        &mut response,
        &request,
        &req_evidence,
        &server_signer(),
        &credential(),
        &delegated_key(),
        DELEGATED_KID,
        CREATED,
        EXPIRES,
    )
    .expect("response signs");

    let rsp_evidence = mcp_re_http_profile::Verifier::new(&VerifierPolicy::default(), &resolver())
        .verify_delegated_bound_response(
            &response,
            &request,
            &expectations(),
            &nothing_revoked,
            NOW,
        )
        .expect("response verifies")
        .signature_facts
        .response_signature_base_digest;

    (
        RetainedHop { request, response },
        req_evidence,
        rsp_evidence,
    )
}

/// R0→S0→R1→S1→R2→S2: two non-terminal turns, each re-linking, then a terminal one.
fn three_hop_chain() -> Vec<RetainedHop> {
    let (h0, r0, s0) = hop("retained-n0", None, AWAITING);
    let (h1, r1, s1) = hop(
        "retained-n1",
        Some(HttpContinuation::from_handles(
            to_digest(&r0),
            to_digest(&s0),
            b"state-0",
        )),
        AWAITING,
    );
    let (h2, _, _) = hop(
        "retained-n2",
        Some(HttpContinuation::from_handles(
            to_digest(&r1),
            to_digest(&s1),
            b"state-1",
        )),
        DONE,
    );
    vec![h0, h1, h2]
}

// ---------------------------------------------------------------------------
// The corpus on disk
// ---------------------------------------------------------------------------

/// One retained HTTP message, as the artifact records it.
///
/// The MESSAGES, not handles. That is the whole difference from the frozen `s01` artifact
/// and the reason a submission digest is reproducible here at all.
#[derive(serde::Serialize, serde::Deserialize)]
struct WireMessage {
    #[serde(skip_serializing_if = "Option::is_none")]
    method: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    target_uri: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    status: Option<u16>,
    headers: Vec<(String, String)>,
    body_b64: String,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct WireHop {
    request: WireMessage,
    response: WireMessage,
}

fn to_wire_request(r: &HttpRequest) -> WireMessage {
    WireMessage {
        method: Some(r.method.clone()),
        target_uri: Some(r.target_uri.clone()),
        status: None,
        headers: r.headers.clone(),
        body_b64: mcp_re_core::b64url_encode(&r.body),
    }
}

fn to_wire_response(r: &HttpResponse) -> WireMessage {
    WireMessage {
        method: None,
        target_uri: None,
        status: Some(r.status),
        headers: r.headers.clone(),
        body_b64: mcp_re_core::b64url_encode(&r.body),
    }
}

fn from_wire_request(w: &WireMessage) -> HttpRequest {
    HttpRequest {
        method: w.method.clone().expect("a retained request names a method"),
        target_uri: w
            .target_uri
            .clone()
            .expect("a retained request names a target"),
        headers: w.headers.clone(),
        body: mcp_re_core::b64url_decode(&w.body_b64).expect("body decodes"),
    }
}

fn from_wire_response(w: &WireMessage) -> HttpResponse {
    HttpResponse {
        status: w.status.expect("a retained response names a status"),
        headers: w.headers.clone(),
        body: mcp_re_core::b64url_decode(&w.body_b64).expect("body decodes"),
    }
}

/// Where the corpus lives, under Cargo and under Bazel.
///
/// The same dual-mode bridge the interop corpus uses: Bazel stages the vectors as runfiles
/// and names the manifest through `MCP_RE_SCITT_RETAINED_MANIFEST`, so the directory is
/// derived from that rather than from `CARGO_MANIFEST_DIR`, which is a source path the
/// sandbox does not have.
fn corpus_dir() -> PathBuf {
    if let Ok(rel) = std::env::var("MCP_RE_SCITT_RETAINED_MANIFEST") {
        for key in ["TEST_SRCDIR", "RUNFILES_DIR"] {
            if let Ok(root) = std::env::var(key) {
                let candidate = std::path::Path::new(&root).join(&rel);
                if candidate.exists() {
                    return candidate.parent().expect("manifest parent").to_path_buf();
                }
            }
        }
        let candidate = PathBuf::from(&rel);
        if candidate.exists() {
            return candidate.parent().expect("manifest parent").to_path_buf();
        }
        panic!("MCP_RE_SCITT_RETAINED_MANIFEST set but runfile not found (rel={rel})");
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("vectors")
        .join("scitt")
        .join("retained")
}

fn artifact(name: &str) -> Vec<u8> {
    std::fs::read(corpus_dir().join(name)).unwrap_or_else(|e| panic!("{name}: {e}"))
}

fn retained_hops() -> Vec<RetainedHop> {
    let wire: Vec<WireHop> =
        serde_json::from_slice(&artifact("retained-hops.json")).expect("retained hops parse");
    wire.iter()
        .map(|h| RetainedHop {
            request: from_wire_request(&h.request),
            response: from_wire_response(&h.response),
        })
        .collect()
}

fn statement() -> SignedStatement {
    SignedStatement::from_cose(&artifact("signed-statement.cbor")).expect("statement parses")
}

/// Reconstruct the record an auditor holds from the retained MESSAGES.
fn reconstruct(hops: &[RetainedHop]) -> mcp_re_http_profile::chain::ChainReconstruction {
    let policy = VerifierPolicy::default();
    let resolve = resolver();
    let verifier = mcp_re_http_profile::Verifier::new(&policy, &resolve);
    reconstruct_chain(
        hops,
        &verifier,
        &expectations(),
        &audit(),
        &nothing_revoked,
        NOW,
    )
}

fn sign_statement(bytes: &[u8]) -> Result<Vec<u8>, HttpProfileError> {
    // `SigningKey::sign` answers base64url; the COSE structure carries raw signature bytes.
    mcp_re_core::b64url_decode(&issuer_key().sign(bytes))
        .map_err(|_| HttpProfileError::MalformedEvidence("issuer signature encoding"))
}

// ---------------------------------------------------------------------------
// The frozen runner
// ---------------------------------------------------------------------------

/// The verdict the frozen corpus cannot reach, over bytes MCP-RE produced.
///
/// `BoundToVerifiedCall` is the whole point: the statement identifies a submission, the
/// retained messages reproduce that identity, and every hop verified — so the record is
/// bound to a call that happened rather than merely to bytes an issuer saw.
#[test]
fn the_committed_corpus_binds_its_statement_to_a_verified_call() {
    let hops = retained_hops();
    assert_eq!(hops.len(), 3, "the corpus is the three-hop chain");
    let reconstruction = reconstruct(&hops);
    assert_eq!(
        reconstruction.label(),
        &ChainLabel::Complete,
        "every hop of the committed corpus must verify"
    );
    assert!(
        !reconstruction.submitted_commitment().is_empty(),
        "a reconstruction from retained MESSAGES identifies its submission"
    );

    let statement = statement();
    assert!(
        statement.commitment().identifies_a_submission(),
        "the committed statement is a post-revision record"
    );
    assert_eq!(
        verify_retained_evidence(statement.commitment(), &reconstruction, None, None)
            .expect("the committed corpus corresponds"),
        RetainedCorrespondence::BoundToVerifiedCall
    );
}

/// A tampered retained body is refused, and refused for the right reason.
///
/// The submission digest is over the SUBMITTED bytes, so altering one changes the identity
/// the statement named — before any question of whether the altered hop still verifies.
#[test]
fn a_tampered_retained_body_no_longer_corresponds() {
    let mut hops = retained_hops();
    hops[2].response.body.push(b' ');
    let reconstruction = reconstruct(&hops);
    let untampered = reconstruct(&retained_hops());
    assert_ne!(
        reconstruction.submitted_commitment(),
        untampered.submitted_commitment(),
        "a changed submitted byte must change the identity"
    );
    verify_retained_evidence(statement().commitment(), &reconstruction, None, None)
        .expect_err("a tampered record must not correspond");
}

/// A truncated record is refused even though its prefix matches.
///
/// The label is inside what the commitment covers, so a record that stops early is a
/// different record — which is the property the whole `submitted_commitment` revision
/// exists to make checkable on the hops after the verified prefix.
#[test]
fn a_truncated_corpus_no_longer_corresponds() {
    let hops = retained_hops();
    let reconstruction = reconstruct(&hops[..2]);
    verify_retained_evidence(statement().commitment(), &reconstruction, None, None)
        .expect_err("a truncated record must not correspond");
}

/// The committed bytes are what this implementation emits today.
///
/// Not a tautology: it compares the FROZEN artifact against a fresh generation, so a change
/// in what MCP-RE produces shows up here rather than being absorbed by regenerating the
/// corpus and the expectation together.
#[test]
fn the_committed_bytes_are_the_ones_this_implementation_produces() {
    let (regenerated_hops, regenerated_statement) = generate();
    assert_eq!(
        serde_json::to_vec_pretty(&regenerated_hops).expect("hops encode"),
        artifact("retained-hops.json"),
        "the committed retained hops are not what this implementation emits; regenerate \
         with `write_retained_corpus -- --ignored --exact` and review the diff"
    );
    assert_eq!(
        regenerated_statement,
        artifact("signed-statement.cbor"),
        "the committed statement is not what this implementation emits"
    );
}

// ---------------------------------------------------------------------------
// The writer
// ---------------------------------------------------------------------------

/// Build the corpus from the shipped signers, verifier and issuer.
fn generate() -> (Vec<WireHop>, Vec<u8>) {
    let hops = three_hop_chain();
    let reconstruction = reconstruct(&hops);
    assert_eq!(
        reconstruction.label(),
        &ChainLabel::Complete,
        "the generated chain must verify end to end"
    );
    let commitment = EvidenceCommitment::from_reconstruction(&reconstruction, None, None);
    let statement = mcp_re_http_profile::scitt::issue_signed_statement(
        ISSUER_KID,
        commitment,
        NOW,
        sign_statement,
    )
    .expect("the statement issues");
    let wire = hops
        .iter()
        .map(|h| WireHop {
            request: to_wire_request(&h.request),
            response: to_wire_response(&h.response),
        })
        .collect();
    (wire, statement.to_cose().to_vec())
}

#[test]
#[ignore = "corpus writer; run with --ignored to regenerate"]
fn write_retained_corpus() {
    let dir = corpus_dir();
    std::fs::create_dir_all(&dir).expect("corpus dir");
    let (hops, statement) = generate();
    std::fs::write(
        dir.join("retained-hops.json"),
        serde_json::to_vec_pretty(&hops).expect("hops encode"),
    )
    .expect("write hops");
    std::fs::write(dir.join("signed-statement.cbor"), &statement).expect("write statement");
    let manifest = serde_json::json!({
        "schema": "mcp-re-scitt-retained/v1",
        "produced_by": "mcp-re-conformance write_retained_corpus (this repository)",
        "establishes": "retained-evidence correspondence over a real MCP-RE multi-hop call: \
                        the statement identifies the submission the retained messages \
                        reproduce, and every hop verified",
        "does_not_establish": "interoperability — every byte here is MCP-RE's own; that is \
                               the interop corpus's question and this does not answer it. \
                               Nothing about registration, a transparency service, or the \
                               confidentiality of retained evidence.",
        "artifacts": {
            "retained-hops.json": hex_sha256(
                &serde_json::to_vec_pretty(&hops).expect("hops encode")
            ),
            "signed-statement.cbor": hex_sha256(&statement),
        }
    });
    std::fs::write(
        dir.join("manifest.json"),
        serde_json::to_vec_pretty(&manifest).expect("manifest encodes"),
    )
    .expect("write manifest");
    eprintln!("wrote the retained corpus into {}", dir.display());
}

fn hex_sha256(bytes: &[u8]) -> String {
    use sha2::Digest;
    let mut hasher = sha2::Sha256::new();
    hasher.update(bytes);
    hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

/// The manifest is a description of the artifacts, and it must describe THESE artifacts.
#[test]
fn the_manifest_describes_the_committed_artifacts() {
    let manifest: serde_json::Value =
        serde_json::from_slice(&artifact("manifest.json")).expect("manifest parses");
    assert_eq!(
        manifest["artifacts"]["retained-hops.json"].as_str(),
        Some(hex_sha256(&artifact("retained-hops.json")).as_str())
    );
    assert_eq!(
        manifest["artifacts"]["signed-statement.cbor"].as_str(),
        Some(hex_sha256(&artifact("signed-statement.cbor")).as_str())
    );
    assert!(
        manifest["produced_by"]
            .as_str()
            .is_some_and(|s| s.contains("this repository")),
        "the manifest must say whose bytes these are — it is the one thing that \
         distinguishes this corpus from the interop one"
    );
}
