import { defineConfig } from "vitest/config";

// The native addon + compiled TS must be built before tests run (npm test does this).
// Tests import the built package from ./dist and the native binding from ./native.
export default defineConfig({
  test: {
    include: ["test/**/*.test.ts"],
    environment: "node",
    // The native addon calls JS callbacks synchronously; keep a single fork so the
    // Node main thread owns them (no worker threading around the .node boundary).
    // Vitest 4 removed poolOptions.forks.singleFork; fileParallelism:false is the
    // replacement — all test files run sequentially in one fork.
    pool: "forks",
    fileParallelism: false,
    coverage: {
      provider: "v8",
      // Only hand-written SDK source is measured. `native/binding.js` is generated by
      // @napi-rs/cli and is a platform loader: it probes every OS/arch/libc combination
      // to find the right .node, so most of it is unreachable on any single machine and
      // scoring it says nothing about this SDK's tests. The Rust behind it is covered by
      // the cargo suites in the root workspace.
      include: ["src/**/*.ts"],
      exclude: ["src/lib.rs", "dist/**", "native/**"],
      reporter: ["text", "lcov"],
      // The repo-wide bar. Below it, `vitest run --coverage` fails.
      thresholds: {
        statements: 90,
        branches: 90,
        functions: 90,
        lines: 90,
      },
    },
  },
});
