"""Response-verification parity tests (Commit A of the response side, #199).

`verify_response` runs the proxy's return-leg chain: verify_signed_response →
classify_response_result → decide → audit_for_decision. A fail-closed verification
is a *result* (carrying the frozen `mcp-re.*` wire reason), not an exception.

`tests/fixtures/verify_response_vectors.json` is generated by the independent Rust
oracle (`cargo run --example gen_response_vector`), which runs the same chain over
valid + malformed responses and records the exact decision/reason. Each scenario
here asserts the Python binding reproduces that outcome.

Regenerate after any envelope/verification change::

    cargo run --example gen_response_vector > tests/fixtures/verify_response_vectors.json
"""

import json
from pathlib import Path

import pytest

import mcp_re_sdk

FIXTURE = Path(__file__).parent / "fixtures" / "verify_response_vectors.json"
VECTORS = json.loads(FIXTURE.read_text())
SERVER = VECTORS["server"]


def _resolver_public_key():
    """The real verifier path: register the server by its raw public key."""
    r = mcp_re_sdk.TrustResolver()
    r.insert_public_key(
        SERVER["signer_id"], SERVER["key_id"], bytes.fromhex(SERVER["public_key_hex"])
    )
    return r


def _run(scenario, resolver):
    p = scenario["params"]
    return mcp_re_sdk.verify_response(
        scenario["response_bytes"].encode(),
        resolver=resolver,
        expected_request_hash=p["expected_request_hash"],
        expected_canonicalization_id=p["expected_canonicalization_id"],
        expected_server_signer=p["expected_server_signer"],
        enforcement_mode=p["enforcement_mode"],
        legacy_allowed=p["legacy_allowed"],
    )


@pytest.mark.parametrize("scenario", VECTORS["scenarios"], ids=lambda s: s["name"])
def test_verify_response_matches_oracle(scenario):
    """Each scenario (valid, unsigned-under-require_mcp_re, tampered, unresolvable
    signer, request_hash mismatch, canonicalization mismatch, pinned-signer
    mismatch) reproduces the mcp-re-client-core chain's decision exactly."""
    res = _run(scenario, _resolver_public_key())
    exp = scenario["expected"]
    assert res.decision == exp["decision"]
    assert res.path == exp["path"]
    assert res.outcome == exp["outcome"]
    assert res.reason == exp["reason"]
    assert res.server_signer == exp["server_signer"]
    assert res.key_id == exp["key_id"]
    assert res.request_hash == exp["request_hash"]
    assert res.accepted == exp["accepted"]


def _valid_scenario():
    return next(s for s in VECTORS["scenarios"] if s["name"] == "valid")


def test_valid_response_accepted_and_binds_request():
    res = _run(_valid_scenario(), _resolver_public_key())
    assert res.accepted and res.decision == "accept"
    assert res.path == "mcp-re-verified"
    assert res.server_signer == SERVER["signer_id"]
    assert res.request_hash == VECTORS["client_request_hash"]


def test_dev_seed_path_matches_public_key_path():
    """insert_dev_seed (test convenience) derives the same public key as
    insert_public_key — identical acceptance. Dev-seed is a test/dev input only;
    verifiers consume public keys, never private material."""
    r = mcp_re_sdk.TrustResolver()
    r.insert_dev_seed(SERVER["signer_id"], SERVER["key_id"], bytes.fromhex(SERVER["seed_hex"]))
    res = _run(_valid_scenario(), r)
    assert res.accepted
    assert res.server_signer == SERVER["signer_id"]


def test_unregistered_signer_fails_closed():
    """An empty resolver cannot resolve the server signer → fail closed."""
    res = _run(_valid_scenario(), mcp_re_sdk.TrustResolver())
    assert res.decision == "fail-closed"
    assert res.reason == "mcp-re.actor_binding_failed"


def test_bad_public_key_length_rejected():
    r = mcp_re_sdk.TrustResolver()
    with pytest.raises(ValueError, match="public_key must be exactly 32 bytes"):
        r.insert_public_key("did:example:server", "k", b"\x00" * 16)


def test_bad_enforcement_mode_rejected():
    valid = _valid_scenario()
    with pytest.raises(ValueError, match="enforcement_mode must be"):
        mcp_re_sdk.verify_response(
            valid["response_bytes"].encode(),
            resolver=_resolver_public_key(),
            expected_request_hash=valid["params"]["expected_request_hash"],
            enforcement_mode="bogus",
        )
