# SPDX-License-Identifier: Apache-2.0
"""Which tracked Lean files a unit's extracted-model evidence is elaborated from.

# The gap this closes

`lean_theorems` is a list of NAMES — `['MCPRE.Time.civil_from_days_total']`. The text those
names denote lives in `verification/lean/theorems/`, which is hand-written, is not
regenerated by CI, and was in no unit's `paths` and no fingerprint component. So

    theorem civil_from_days_total : True := trivial

resolves under the same name, reports an EMPTY axiom closure — inside the kernel baseline,
therefore accepted — and leaves the standing `lean` PASS deriving FRESH. The claim had been
emptied and the fingerprint had not moved. That is the defect encoding v4 repaired for tests
(`test_evidence_definition` named the battery; `test_sources` measures it), one level up: at
the CLAIM rather than at the instrument.

`check-assumptions` does scan these files, for `sorry`, `axiom`, `assume` and `admit`, so
the SEAM path was covered. A statement weakened without a seam contains none of those
tokens.

# The cone is the one the LANE elaborates

Not per theorem. `lake build` builds the package's default target and everything it imports,
and the axiom query imports every lakefile root, so what the recorded PASS was measured
against is the package — and a fingerprint narrower than the measured cone lets source the
proof stands on change while the graph still answers FRESH. The same argument puts a whole
crate in a Verus unit's `source_inputs`.

So the population is derived from the build definition: start at every `[[lean_lib]]` root,
follow `import` transitively, and keep the modules that resolve to a tracked file inside one
of the package's source directories. A module that resolves to nothing is Aeneas or Mathlib
— external, and pinned by `toolchain_identity` rather than digested here.

# Two halves, because they have different owners

`verification/lean/generated/` is machine-owned and `verification/lean/theorems/` is
hand-written, and the lakefile keeps them in separate `srcDir`s precisely so that "was this
written by a person" is a question about which directory a file is in. The split is kept
here: the handwritten half is the CLAIM (`lean_theorem_sources`) and the generated half is
the extracted MODEL the claim is about (`generated_inputs`).

# This module is part of the ENCODING, not of the instrument

For the reason `_fingerprint.py` itself is excluded from `test_lane_identity`: a change of
meaning here must move `ENCODING_VERSION`, and digesting the file would additionally
invalidate every lean unit for a comment. It reads the lakefile through `_lean_model`'s own
parser rather than a second one — `lean_libs` is the build definition's only reader.
"""

from __future__ import annotations

import re

from _lean_model import LEAN_DIR, lean_libs
from _manifest import ManifestError, REPO_ROOT

#: The machine-owned source directory. Everything else a `[[lean_lib]]` names is written by
#: a person.
GENERATED_SRCDIR = "generated"

#: `import Foo.Bar` at the head of a Lean module. Leading whitespace is allowed because a
#: file may be preceded by a licence comment; a trailing `import` inside a comment would
#: over-approximate, which is the safe direction.
IMPORT = re.compile(r"^\s*import\s+([A-Za-z_][A-Za-z0-9_.']*)", re.M)


def _module_file(src_dir: str, module: str) -> str | None:
    """The repo-relative path `module` resolves to inside `src_dir`, or None."""
    rel = f"{src_dir}/{module.replace('.', '/')}.lean"
    path = LEAN_DIR / rel
    if not path.is_file():
        return None
    return path.relative_to(REPO_ROOT).as_posix()


def _resolve(module: str) -> tuple[str, str] | None:
    """`(srcDir, path)` for a module the package itself defines, else None.

    None means EXTERNAL — Aeneas, Mathlib, Lean core — whose identity is carried by the
    toolchain pins, not by a digest of files this repository does not contain.
    """
    for src_dir, _roots in lean_libs():
        found = _module_file(src_dir, module)
        if found is not None:
            return src_dir, found
    return None


def lean_closure() -> dict[str, str]:
    """Every tracked package file the lakefile's roots reach, mapped to its `srcDir`.

    Fail-closed on a declared ROOT that resolves to nothing: the lakefile says the package
    builds that module, so a missing file is a broken package, and returning a smaller set
    would let the fingerprint quietly measure less than the lane elaborates. An unresolvable
    IMPORT is a different fact — it is how an external dependency looks — and is skipped.
    """
    libs = lean_libs()
    if not libs:
        raise ManifestError(
            f"{LEAN_DIR.relative_to(REPO_ROOT).as_posix()}/lakefile.toml declares no "
            "`[[lean_lib]]`, so nothing says which modules the extraction lanes elaborate. "
            "A unit claiming `lean://` cannot be fingerprinted against a package that does "
            "not define itself."
        )
    pending: list[str] = []
    for src_dir, roots in libs:
        for root in roots:
            if _module_file(src_dir, root) is None:
                raise ManifestError(
                    f"lakefile.toml builds `{root}` out of `{src_dir}/`, and that module "
                    f"resolves to no file. The package's own build definition names it, so "
                    f"this is a broken package rather than an absent optional input."
                )
            pending.append(root)

    seen: dict[str, str] = {}
    while pending:
        module = pending.pop()
        resolved = _resolve(module)
        if resolved is None:
            continue
        src_dir, path = resolved
        if path in seen:
            continue
        seen[path] = src_dir
        text = (REPO_ROOT / path).read_text(encoding="utf-8")
        pending += IMPORT.findall(text)
    return dict(sorted(seen.items()))


def theorem_source_paths() -> list[str]:
    """The hand-written half of the closure — the files the CLAIMS are stated in."""
    return [p for p, src in lean_closure().items() if src != GENERATED_SRCDIR]


def generated_model_paths() -> list[str]:
    """The machine-owned half — the extracted model the claims are proved ABOUT."""
    return [p for p, src in lean_closure().items() if src == GENERATED_SRCDIR]


#: The build definition itself. It decides which modules are roots, which directory each
#: library reads, and therefore what the two halves above CONTAIN — so a change to it
#: changes the selection even when every file it names is untouched. Digested with the
#: handwritten half rather than separately: it is hand-written, and one entry is one fact.
LAKEFILE = "verification/lean/lakefile.toml"
