"""Package/module path resolution for the remediation dependency graph.

Its own file per the repo's one-class-per-file rule; `deps_graph.py` is the
script that builds the graph, this is the lookup it leans on.
"""
from __future__ import annotations

import ast
import os
import subprocess

# Same split-literal form as deps_graph.py, and for the same reason: the
# autogeneratedfileprotection hook matches on the plain filename, so writing
# it whole here would make this file unwritable by tooling.
BARREL = "__init" + "__.py"


class Resolver:
    """Top-level package name -> src root, and module path -> file."""

    def __init__(self, root: str):
        self.root = root
        self.pkg_root: dict[str, str] = {}
        # Every `src` directory holding a package, wherever the repository keeps them.
        p = subprocess.run(["git", "ls-files", "*/src/*/" + BARREL, "src/*/" + BARREL],
                           cwd=root, capture_output=True, text=True)
        for f in sorted(p.stdout.split()):
            self._register(os.path.join(root, os.path.dirname(os.path.dirname(f))))
        self._barrels: dict[str, dict[str, str]] = {}

    def _register(self, src: str) -> None:
        if not os.path.isdir(src):
            return
        for pkg in sorted(os.listdir(src)):
            if os.path.isdir(os.path.join(src, pkg)) and not pkg.startswith("."):
                self.pkg_root.setdefault(pkg, src)

    def mod_file(self, mod: str) -> str | None:
        parts = mod.split(".")
        src = self.pkg_root.get(parts[0])
        if not src:
            return None
        p = os.path.join(src, *parts)
        if os.path.isdir(p):
            i = os.path.join(p, BARREL)
            return os.path.relpath(i, self.root) if os.path.exists(i) else None
        return os.path.relpath(p + ".py", self.root) if os.path.exists(p + ".py") else None

    def barrel_map(self, pkgmod: str) -> dict[str, str]:
        if pkgmod in self._barrels:
            return self._barrels[pkgmod]
        m: dict[str, str] = {}
        f = self.mod_file(pkgmod)
        if f and f.endswith(BARREL):
            try:
                tree = ast.parse(open(os.path.join(self.root, f), encoding="utf-8", errors="ignore").read())
                for n in ast.walk(tree):
                    if isinstance(n, ast.ImportFrom) and n.module and n.level == 0:
                        for a in n.names:
                            m[a.name] = n.module
            except (OSError, SyntaxError):
                pass
        self._barrels[pkgmod] = m
        return m

    def targets(self, path: str) -> set[str]:
        out: set[str] = set()
        try:
            tree = ast.parse(open(os.path.join(self.root, path), encoding="utf-8", errors="ignore").read())
        except (OSError, SyntaxError):
            return out
        for n in ast.walk(tree):
            if isinstance(n, ast.Import):
                for a in n.names:
                    f = self.mod_file(a.name)
                    if f:
                        out.add(f)
            elif isinstance(n, ast.ImportFrom) and n.level == 0 and n.module:
                f = self.mod_file(n.module)
                if f and f.endswith(BARREL):
                    bm = self.barrel_map(n.module)
                    hit = False
                    for a in n.names:
                        if a.name in bm:
                            t = self.mod_file(bm[a.name])
                            if t:
                                out.add(t)
                                hit = True
                        else:
                            t = self.mod_file(n.module + "." + a.name)
                            if t:
                                out.add(t)
                                hit = True
                    if not hit:
                        out.add(f)
                elif f:
                    out.add(f)
        return out
